language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
  - CFLAGS=-std=c99
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-4.8
      - libxtst-dev
      - cmake
      - cmake-data
install:
  - npm install